/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/office/scene.gltf
Author: Kyle Rooze (https://sketchfab.com/KyleRooze)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-hallway-1caff84f3315447088973bcf187234ee
Title: Office Hallway
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.StingrayPBS1SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.StingrayPBS2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.StingrayPBS3SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.StingrayPBS3SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.StingrayPBS4SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.StingrayPBS4SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.StingrayPBS4SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.StingrayPBS4SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.StingrayPBS4SG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.StingrayPBS5SG} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.StingrayPBS6SG} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.StingrayPBS7SG} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.StingrayPBS7SG} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.StingrayPBS7SG} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.StingrayPBS7SG} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.StingrayPBS7SG} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.StingrayPBS7SG} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.StingrayPBS8SG} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.StingrayPBS8SG} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.StingrayPBS9SG} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.StingrayPBS9SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
